title: Thomas Zaborenko
logo: docs/assets/profile_pic_circle.png
description: Resume* | <a href="https://www.linkedin.com/in/thomas-zabo/">LinkedIn</a> | <a href="https://www.quantconnect.com/u/thomas-zaborenko">QuantConnect</a>
#show_downloads: true
theme: jekyll-theme-minimal
