title: Thomas Zaborenko
logo: docs/assets/profile_pic_circle.png
description: Resume* | [LinkedIn](https://www.linkedin.com/in/thomas-zabo/) | [QuantConnect](https://www.quantconnect.com/u/thomas-zaborenko)
#show_downloads: true
theme: jekyll-theme-minimal
