title: <div align="center">Thomas Zaborenko</div>
logo: docs/assets/profile_pic_circle.png
description: <div align="center"> <a href="docs/assets/ThomasZaborenkoResume2024.pdf">Resume</a> | <a href="https://www.linkedin.com/in/thomas-zabo/">LinkedIn</a> | <a href="https://www.quantconnect.com/u/thomas-zaborenko">QuantConnect</a></div>
#show_downloads: true
theme: jekyll-theme-minimal
